### ISSUE TITLE
Region display selectors

### ISSUE THREAD

**Issue by mpanoratra** [mpanoratra/cs347_final_project#9]

**Comment by brianquimio** [comment]
For Each Page:
• Under Regions, click on “Lab Report”
• Go to the Attributes Tab
• Change “Region Display Sector” to “Yes”. Click Apply Changes 
• Under Regions, click “+” to add a new Region
• Select “Region Display Sector” near the bottom right
• Click Create
To remove the ‘Show All’ button 
• Under Regions, click on “Region Display Sector”
• Click on Region Attributes. Change “Include Show All” to “No”

Don’t really see the use of this, since we’re only having one region per page unless we implement a chart. Or am I not understanding it correctly?
